baseURL = "https://paul-lysak.github.io/"
languageCode = "en-us"
title = "Ambiguous Implicits - Paul Lysak's blog about programming"
theme = "hugo_theme_beg"
SectionPagesMenu = "main"
googleAnalytics = "UA-98972707-1"
[Params]
  description = "Paul Lysak blog"
  Author = "Paul Lysak"
[taxonomies]
 year = "years"
 tag = "tags"
# category = "categories"
[[menu.main]]
        name = "About"
        weight = -110
        identifier = "about"
        url = "/about/"

